### PR TITLE
upgrade to .NET 8, update dependencies, update search for nupkg and nuspec

### PR DESCRIPTION
**Pull request by danielklecha**
1. I couldn't build some of the .NET Core projects til I updated the references
2. I switched to Central Package Management (with Directory.Packages.props) because it allows to use the latest versions of transitive packages.
3. I updated .NET to version 8. I also updated GitHub action.
4. I updated GitHub service because sometimes the license is not available in the repository and I got 404.
5. I updated the search for nupkg and nuspec. I noticed that nuget uses two types of structures in packages folder. I used regex to detect the currently used structure. The previous implementation didn't work for me for .NET Framework 4.8 projects.
6. I updated the version to 0.2.8

### CODE REVIEW

**Comment by danielklecha** [comment]
I found few small issues. I need to analyze it :)

**Comment by danielklecha** [comment]
I fixed issues with the detection of the package folder and the detection of the license next to the dll.

**Comment by danielklecha** [comment]
@bugproof Could you merge my changes? I have few other ideas but I think that this package of changes is complete.

**Comment by bugproof** [comment]
Nice job. I added you as collaborator so you can merge stuff yourself now (I think)

**Pull request merged**
